// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Wren
{
    internal sealed partial class Vsix
    {
        public const string Id = "Wren.a965bd57-3def-470f-b038-499c461e6de3";
        public const string Name = "Wren";
        public const string Description = @"Visual Studio syntax highlighting support for Wren (.wren) files";
        public const string Language = "en-US";
        public const string Version = "1.0.1";
        public const string Author = "Mads Kristensen";
        public const string Tags = "env, environment";
    }
}
